export const INICIO_CARGANDO_MESAS = 'INICIO_CARGANDO_MESAS';
export const FIN_CARGANDO_MESAS = 'FIN_CARGANDO_MESAS';
export const SET_MESAS = 'SET_MESAS';
export const SET_SELECCIONAR_MESA = 'SET_SELECCIONAR_MESA';
